PROJECT_HOME = ../../COMMON
LKH_LIB = $(PROJECT_HOME)/libLKHSym.a
LKH_LIB_FLAG = -lLKHSym
EXE = cvrp
#DEBUG = -g -fno-omit-frame-pointer #-fsanitize=address
#DEBUG = -g -O0 -fno-omit-frame-pointer #-fsanitize=address

include $(PROJECT_HOME)/Common.mk