PROJECT_HOME = ../../COMMON
LKH_LIB = $(PROJECT_HOME)/libLKHAsym.a
LKH_LIB_FLAG = -lLKHAsym
EXE = cvrptw
#DEBUG = -fprofile-use=/home/cava/Uni/LKH-SP/CVRPTW/.profile/#-fprofile-generate=.profile #-g -fno-omit-frame-pointer -O1
#DEBUG = -fprofile-generate=.profile #-g -fno-omit-frame-pointer -O1

include $(PROJECT_HOME)/Common.mk
